name: COMMUNICO FRONTEND

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.x'
        channel: 'stable'

    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e
          cd /home/as3hr/communico-frontend
          echo "Pulling latest code from GitHub..."
          git fetch origin
          git reset --hard origin/master
          flutter pub get

    - name: Restart Nginx
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Checking Nginx configuration..."
          sudo nginx -t
          echo "Restarting Nginx..."
          sudo systemctl restart nginx