name: COMMUNICO FRONTEND

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'
        dart-version: '3.5.4'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --release

    - name: Debug Flutter Build
      run: |
        echo "Build completed. Checking for files in 'build/web'..."
        ls -la build/web/
    
    - name: Remove existing build/web on VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd /home/as3hr/communico-frontend/
            rm -rf build
      
    - name: Copy build artifacts
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/web/*"
        target: "/home/as3hr/communico-frontend/build/web"

    - name: Restart Nginx
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Testing Nginx configuration..."
          sudo nginx -t
          echo "Restarting Nginx..."
          sudo systemctl restart nginx
