name: COMMUNICO FRONTEND

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'
        dart-version: '3.5.4'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get

    - name: Build Web
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
      run: |
        flutter build web --web-renderer canvaskit --release \
          --dart-define=BASE_URL=$BASE_URL
 
    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/communico-frontend
          git pull origin master

    - name: Remove Build/Web Directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/communico-frontend/build/
          rm -rf web
      
    - name: Copy build artifacts
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/web/*"
        target: "/var/www/html/communico-frontend/"
    
    - name: Restart Nginx
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_PUBLIC_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            sudo nginx -t
            sudo systemctl restart nginx
